channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.0
- pip:
  - mlflow==3.5.0
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==2.2.6
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
